In [1]:
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]

10-element Array{Float64,1}:
 0.1 
 0.05
 0.6 
 0.0 
 0.05
 0.1 
 0.0 
 0.1 
 0.0 
 0.0 

In [2]:
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

10-element Array{Int64,1}:
 0
 0
 1
 0
 0
 0
 0
 0
 0
 0

In [3]:
mean_square_error(y::Vector, t::Vector) = 0.5 * sum((y - t).^2)

mean_square_error (generic function with 1 method)

In [4]:
mean_square_error(y, t)

0.09750000000000003

In [5]:
y2 = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.0, 0.0];

In [6]:
mean_square_error(y2, t)

0.5974999999999999

In [7]:
function cross_entropy_error(y::Vector, t::Vector)
    δ = 1e-7
    return -sum(t .* log.(y .+ δ))
end

cross_entropy_error (generic function with 1 method)

In [8]:
cross_entropy_error(y, t)

0.510825457099338

In [9]:
cross_entropy_error(y2, t)

2.302584092994546

In [10]:
include("dataset/load_mnist.jl")

LoadMnist

In [12]:
(x_train, t_train), (x_test, t_test) = LoadMnist.load_mnist(
    normalize=true, one_hot_label=true)

((Float32[0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 1.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 1.0 0.0]), (Float32[0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0]))

In [13]:
size(x_train)

(784, 60000)

In [14]:
size(t_train)

(60000, 10)

In [15]:
function cross_entropy_error(y::Matrix, t::Matrix)
    δ = 1e-7
    batch_size = size(y)[2]
    return -sum(t .* log.(y .+ δ)) / batch_size
end

cross_entropy_error (generic function with 2 methods)

In [16]:
cross_entropy_error(reshape(y, length(y), 1), reshape(t, length(t), 1))

0.510825457099338

In [19]:
function cross_entropy_error(y::Matrix, t::Vector)
    δ = 1e-7
    batch_size = size(y)[2]
    return -sum(log.(y[[CartesianIndex(i1, i2) for (i1, i2)=zip(t.+1, 1:batch_size)]] .+ δ)) / batch_size
end

cross_entropy_error (generic function with 3 methods)

In [18]:
Y = [y y2;]

10×2 Array{Float64,2}:
 0.1   0.1 
 0.05  0.05
 0.6   0.1 
 0.0   0.0 
 0.05  0.05
 0.1   0.1 
 0.0   0.0 
 0.1   0.6 
 0.0   0.0 
 0.0   0.0 

In [20]:
T = [t t;]

10×2 Array{Int64,2}:
 0  0
 0  0
 1  1
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0

In [21]:
cross_entropy_error(Y, T)

1.406704775046942

In [22]:
cross_entropy_error(Y, [2, 2])

1.406704775046942

In [23]:
function numerical_diff(f, x)
    h = 1e-4
    return (f(x+h) - f(x-h)) / 2h
end

numerical_diff (generic function with 1 method)

In [24]:
function_1(x) = 0.01x^2 + 0.1x

function_1 (generic function with 1 method)

In [25]:
numerical_diff(function_1, 5)

0.1999999999990898

In [26]:
numerical_diff(function_1, 10)

0.2999999999986347

In [27]:
function_2(x0, x1) = x0^2 + x1^2

function_2 (generic function with 1 method)

In [28]:
function_tmp1(x0) = function_2(x0, 4.0)

function_tmp1 (generic function with 1 method)

In [30]:
numerical_diff(function_tmp1, 3.0)

6.00000000000378

In [29]:
function_tmp2(x1) = function_2(3.0, x1)

function_tmp2 (generic function with 1 method)

In [31]:
numerical_diff(function_tmp2, 4.0)

7.999999999999119